# -*- coding: utf-8 -*-
"""ImageClassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDLxop8Th_Mfqug8R7eEp3iK14Sv_wms
"""

import kagglehub
data_path = kagglehub.dataset_download('bhavikjikadara/dog-and-cat-classification-dataset')

import PIL
from PIL import Image
import os

cat_path = '/kaggle/input/dog-and-cat-classification-dataset/PetImages/Cat'
dog_path = '/kaggle/input/dog-and-cat-classification-dataset/PetImages/Dog'

cat_img = os.listdir(cat_path)
dog_img = os.listdir(dog_path)
Image.open(f'{cat_path}/{cat_img[0]}')
Image.open(f'{dog_path}/{dog_img[1]}')

import torch
import torch.nn as nn

import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split

transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

full_data = datasets.ImageFolder(root=f'{data_path}/PetImages/', transform=transform)

print(f"Classes found: {full_data.classes}")

train_size = int(0.8 * len(full_data))
test_size = len(full_data) - train_size

train_dataset, test_dataset = random_split(full_data, [train_size, test_size])

train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False)

print(f"Total images: {len(full_data)}")
print(f"Training set size: {len(train_dataset)}")
print(f"Test set size: {len(test_dataset)}")

class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(128 * 16 * 16, 512)
        self.fc2 = nn.Linear(512, 2)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.pool(self.relu(self.conv1(x))) # 128 -> 64
        x = self.pool(self.relu(self.conv2(x))) # 64 -> 32
        x = self.pool(self.relu(self.conv3(x))) # 32 -> 16
        x = x.view(-1, 128 * 16 * 16)
        x = self.relu(self.fc1(x))
        x = self.fc2(x)
        return x

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = SimpleCNN().to(device)
print(f"Training on device: {device}")

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.002)

# epoch = 5 for v2 and epoch = 15 for v3 in given file
num_epochs = 15

for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {running_loss/len(train_loader):.4f}")

print("Training Finished!")

model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'Accuracy of the model on the test images: {100 * correct / total:.2f}%')

torch.save(model.state_dict(), 'cat_dog_weights_v3.pth')

model.eval()

dummy_input = torch.randn(1, 3, 128, 128).to(device)

traced_model = torch.jit.trace(model, dummy_input)

traced_model.save("cat_dog_portable_v3.pt")
print("Saved portable model!")

